import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Student Registration Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <div className="min-h-screen bg-gray-50 py-8">
          <div className="container mx-auto px-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
